// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {agents} from '../models';

export function AppVersion():Promise<string>;

export function ApplyUpdate():Promise<string>;

export function ArchiveProject(arg1:string,arg2:boolean):Promise<string>;

export function CheckConflicts(arg1:string,arg2:Array<string>,arg3:string):Promise<Array<string>>;

export function CheckUpdate():Promise<model.UpdateInfo>;

export function ChooseFolder(arg1:string):Promise<string>;

export function ConfigPath():Promise<string>;

export function CopyEntries(arg1:string,arg2:Array<string>,arg3:string,arg4:string):Promise<string>;

export function CreateProject(arg1:model.CreateOptions):Promise<string>;

export function DeleteAgentTemplate(arg1:string):Promise<void>;

export function DeleteArchive(arg1:string):Promise<string>;

export function DeleteEntries(arg1:string,arg2:Array<string>):Promise<string>;

export function DeleteEntriesForce(arg1:string,arg2:Array<string>):Promise<string>;

export function GetAgentTemplates():Promise<Array<agents.Template>>;

export function GetConfig():Promise<model.Config>;

export function GetLicenseOptions():Promise<Array<model.LicenseOption>>;

export function GetTaskBoard(arg1:string):Promise<model.TaskBoard>;

export function GitApplyStash(arg1:string,arg2:string):Promise<string>;

export function GitBackups(arg1:string):Promise<Array<model.Backup>>;

export function GitBranches(arg1:string):Promise<Array<model.Branch>>;

export function GitCheckout(arg1:string,arg2:string):Promise<model.OpResult>;

export function GitCommitAll(arg1:string,arg2:string):Promise<string>;

export function GitCommitFiles(arg1:string,arg2:string):Promise<Array<model.FileChange>>;

export function GitCommitPaths(arg1:string,arg2:Array<string>,arg3:string,arg4:boolean):Promise<string>;

export function GitCreateBranch(arg1:string,arg2:string,arg3:boolean):Promise<model.OpResult>;

export function GitCreateTag(arg1:string,arg2:string,arg3:string):Promise<model.OpResult>;

export function GitDeleteBranch(arg1:string,arg2:string,arg3:boolean):Promise<model.OpResult>;

export function GitDiffCommitFile(arg1:string,arg2:string,arg3:string):Promise<model.DiffText>;

export function GitDiffFile(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function GitDiffRefFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<model.DiffText>;

export function GitDiffRefs(arg1:string,arg2:string,arg3:string):Promise<model.DiffSummary>;

export function GitDiscardChanges(arg1:string):Promise<string>;

export function GitDropBackup(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GitFetch(arg1:string,arg2:string,arg3:boolean):Promise<model.OpResult>;

export function GitLog(arg1:string):Promise<Array<model.Commit>>;

export function GitMerge(arg1:string,arg2:string):Promise<model.OpResult>;

export function GitPull(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<model.OpResult>;

export function GitPush(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<model.OpResult>;

export function GitPushTag(arg1:string,arg2:string,arg3:string):Promise<model.OpResult>;

export function GitRemotes(arg1:string):Promise<Array<model.Remote>>;

export function GitRevert(arg1:string,arg2:string):Promise<string>;

export function GitRollback(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function GitSetUpstream(arg1:string,arg2:string,arg3:string):Promise<model.OpResult>;

export function GitTags(arg1:string):Promise<Array<model.Tag>>;

export function GitWorktreeFiles(arg1:string):Promise<Array<model.FileChange>>;

export function ImportProject(arg1:string):Promise<string>;

export function ListArchives():Promise<Array<model.ArchiveEntry>>;

export function ListDir(arg1:string,arg2:string):Promise<model.DirListing>;

export function ListProjects():Promise<Array<model.Project>>;

export function LogPath():Promise<string>;

export function MoveEntries(arg1:string,arg2:Array<string>,arg3:string,arg4:string):Promise<string>;

export function NewFolder(arg1:string,arg2:string,arg3:string):Promise<string>;

export function OpenEditor(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenTerminal(arg1:string):Promise<void>;

export function OpenWithSystem(arg1:string):Promise<void>;

export function PreviewFile(arg1:string,arg2:string):Promise<model.FilePreview>;

export function ReadTextFile(arg1:string,arg2:string,arg3:number):Promise<model.TextFile>;

export function RemoveImportedProject(arg1:string):Promise<string>;

export function RenameEntry(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function RestoreArchive(arg1:string):Promise<string>;

export function SaveAgentTemplate(arg1:string,arg2:string,arg3:string):Promise<agents.Template>;

export function SaveConfig(arg1:model.Config):Promise<model.Config>;

export function SearchAll(arg1:string):Promise<Array<model.SearchHit>>;

export function SetAlias(arg1:string,arg2:string):Promise<string>;

export function SetProjectRoot(arg1:string,arg2:string):Promise<string>;

export function SetTheme(arg1:string):Promise<model.Config>;

export function WriteTextFile(arg1:string,arg2:string,arg3:string):Promise<string>;
