// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function ArchiveProject(arg1, arg2) {
  return window['go']['main']['App']['ArchiveProject'](arg1, arg2);
}

export function CheckConflicts(arg1, arg2, arg3) {
  return window['go']['main']['App']['CheckConflicts'](arg1, arg2, arg3);
}

export function ChooseFolder(arg1) {
  return window['go']['main']['App']['ChooseFolder'](arg1);
}

export function ConfigPath() {
  return window['go']['main']['App']['ConfigPath']();
}

export function CopyEntries(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CopyEntries'](arg1, arg2, arg3, arg4);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function DeleteAgentTemplate(arg1) {
  return window['go']['main']['App']['DeleteAgentTemplate'](arg1);
}

export function DeleteArchive(arg1) {
  return window['go']['main']['App']['DeleteArchive'](arg1);
}

export function DeleteEntries(arg1, arg2) {
  return window['go']['main']['App']['DeleteEntries'](arg1, arg2);
}

export function DeleteEntriesForce(arg1, arg2) {
  return window['go']['main']['App']['DeleteEntriesForce'](arg1, arg2);
}

export function GetAgentTemplates() {
  return window['go']['main']['App']['GetAgentTemplates']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLicenseOptions() {
  return window['go']['main']['App']['GetLicenseOptions']();
}

export function GetTaskBoard(arg1) {
  return window['go']['main']['App']['GetTaskBoard'](arg1);
}

export function GitApplyStash(arg1, arg2) {
  return window['go']['main']['App']['GitApplyStash'](arg1, arg2);
}

export function GitBackups(arg1) {
  return window['go']['main']['App']['GitBackups'](arg1);
}

export function GitBranches(arg1) {
  return window['go']['main']['App']['GitBranches'](arg1);
}

export function GitCheckout(arg1, arg2) {
  return window['go']['main']['App']['GitCheckout'](arg1, arg2);
}

export function GitCommitAll(arg1, arg2) {
  return window['go']['main']['App']['GitCommitAll'](arg1, arg2);
}

export function GitCommitFiles(arg1, arg2) {
  return window['go']['main']['App']['GitCommitFiles'](arg1, arg2);
}

export function GitCommitPaths(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GitCommitPaths'](arg1, arg2, arg3, arg4);
}

export function GitCreateBranch(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitCreateBranch'](arg1, arg2, arg3);
}

export function GitCreateTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitCreateTag'](arg1, arg2, arg3);
}

export function GitDeleteBranch(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitDeleteBranch'](arg1, arg2, arg3);
}

export function GitDiffCommitFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitDiffCommitFile'](arg1, arg2, arg3);
}

export function GitDiffFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitDiffFile'](arg1, arg2, arg3);
}

export function GitDiffRefFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GitDiffRefFile'](arg1, arg2, arg3, arg4, arg5);
}

export function GitDiffRefs(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitDiffRefs'](arg1, arg2, arg3);
}

export function GitDiscardChanges(arg1) {
  return window['go']['main']['App']['GitDiscardChanges'](arg1);
}

export function GitDropBackup(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitDropBackup'](arg1, arg2, arg3);
}

export function GitFetch(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitFetch'](arg1, arg2, arg3);
}

export function GitLog(arg1) {
  return window['go']['main']['App']['GitLog'](arg1);
}

export function GitMerge(arg1, arg2) {
  return window['go']['main']['App']['GitMerge'](arg1, arg2);
}

export function GitPull(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GitPull'](arg1, arg2, arg3, arg4);
}

export function GitPush(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GitPush'](arg1, arg2, arg3, arg4);
}

export function GitPushTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitPushTag'](arg1, arg2, arg3);
}

export function GitRemotes(arg1) {
  return window['go']['main']['App']['GitRemotes'](arg1);
}

export function GitRevert(arg1, arg2) {
  return window['go']['main']['App']['GitRevert'](arg1, arg2);
}

export function GitRollback(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitRollback'](arg1, arg2, arg3);
}

export function GitSetUpstream(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitSetUpstream'](arg1, arg2, arg3);
}

export function GitTags(arg1) {
  return window['go']['main']['App']['GitTags'](arg1);
}

export function GitWorktreeFiles(arg1) {
  return window['go']['main']['App']['GitWorktreeFiles'](arg1);
}

export function ImportProject(arg1) {
  return window['go']['main']['App']['ImportProject'](arg1);
}

export function ListArchives() {
  return window['go']['main']['App']['ListArchives']();
}

export function ListDir(arg1, arg2) {
  return window['go']['main']['App']['ListDir'](arg1, arg2);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function LogPath() {
  return window['go']['main']['App']['LogPath']();
}

export function MoveEntries(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MoveEntries'](arg1, arg2, arg3, arg4);
}

export function NewFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['NewFolder'](arg1, arg2, arg3);
}

export function OpenEditor(arg1) {
  return window['go']['main']['App']['OpenEditor'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenTerminal(arg1) {
  return window['go']['main']['App']['OpenTerminal'](arg1);
}

export function OpenWithSystem(arg1) {
  return window['go']['main']['App']['OpenWithSystem'](arg1);
}

export function PreviewFile(arg1, arg2) {
  return window['go']['main']['App']['PreviewFile'](arg1, arg2);
}

export function ReadTextFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadTextFile'](arg1, arg2, arg3);
}

export function RemoveImportedProject(arg1) {
  return window['go']['main']['App']['RemoveImportedProject'](arg1);
}

export function RenameEntry(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RenameEntry'](arg1, arg2, arg3, arg4);
}

export function RestoreArchive(arg1) {
  return window['go']['main']['App']['RestoreArchive'](arg1);
}

export function SaveAgentTemplate(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveAgentTemplate'](arg1, arg2, arg3);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SearchAll(arg1) {
  return window['go']['main']['App']['SearchAll'](arg1);
}

export function SetAlias(arg1, arg2) {
  return window['go']['main']['App']['SetAlias'](arg1, arg2);
}

export function SetProjectRoot(arg1, arg2) {
  return window['go']['main']['App']['SetProjectRoot'](arg1, arg2);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function WriteTextFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteTextFile'](arg1, arg2, arg3);
}
